displayName=Death Dotter
author=Dylan Gearhart
support=https://github.com/dmgear/deathdotterplugin
description=A plugin that conditionally renders other players when occupying the same tile
tags=pvp,dd,nh,no honor,no honour,oda,stake,deathdot
plugins=DeathDotter.DeathDotterPlugin
